example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit/', add_wishlist, name='add_wishlist')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import render, redirect
from wishlist.models import BarangWishlist
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
import datetime

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Hayfa Najma',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def wishlist_ajax(request):
    context = {
        'nama': 'Hayfa Najma',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
@csrf_exempt
def add_wishlist(req):
    if req.method == "POST":
        nama = req.POST.get("nama")
        harga = req.POST.get("harga")
        deskripsi = req.POST.get("deskripsi")
        BarangWishlist.objects.create(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)
        return HttpResponse()
    else:
        print("here")
        return redirect("wishlist:show_wishlist")

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    # Jika JSON
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<link rel="stylesheet" href="{% static 'login.css' %}" />

<div class = "login-box">
    <h2>Login</h2>
    <form method="POST" action="">
        {% csrf_token %}
        
        <div class="user-box">
            <input type="text" name="username" required="">
            <label>Username</label>
        </div>

        <div class="user-box">
            <input type="password" name="password" required="">
            <label>Password</label>
        </div>

        <button class="submit" type="text">LOGIN</button>
        <a href="{% url 'wishlist:register' %}">REGISTER</a>

        {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}  
         
    </form>
</div>
{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Wishlist</title>
{% endblock meta %}

{% block content %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'wishlist.css' %}" />

  <title>Wishlist</title>
</head>

<body>
  <nav class="navbar navbar-expand-md justify-content-center" style="background-color: #FFC4C4;">
      <div class="navbar-nav mr-auto">
          <b><a class="navbar-brand" href="#" style="color: black">Wishlist 😎🤹🏻</a></b>
      </div>
      <div class="mx-auto order-0">
        <b><a class="navbar-brand" href="#" style="color: black">Home</a></b>
      </div>

      <div class="navbar-nav ml-auto">
          <b><a class="navbar-brand" href="#" style="color: black">{{nama}}</a></b>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <button class="btn btn-light"><a href="{% url 'wishlist:logout' %}" style="color: black">Logout</a></button>
      </div>
  </nav>

  <div class="row justify-content-center mt-md-5">
      <div class="col-auto ">
          <h3><Center>Selamat Datang di Wishlist!</Center></h3>
          <table class="table text-center table-bordered">
                  <tr style="background-color:bisque;">
                  <th>Nama Barang</th>
                  <th>Harga Barang</th>
                  <th>Deskripsi</th>
                  </tr>
              </thead>

              <tbody class="">
                  {% for barang in list_barang %}
                      <tr style="background-color: #FFF5E4;">
                          <td>{{barang.nama_barang}}</td>
                          <td>{{barang.harga_barang}}</td>
                          <td>{{barang.deskripsi}}</td>
                      </tr>
                  {% endfor %}
              </tbody>

          </table>
          
          <h5 style="border: black;"><center>Sesi terakhir login: {{ last_login }}</center></h5>
      </div>
  </div>
</body>

<style>
  .col-auto h3 {
    font-size: 50px;
    font-weight: bold;
  }

  h3 {
      padding-bottom: 20px;
  }
  .table-bordered tbody tr {
      border: 3px solid black;
  }

  .table-bordered tbody tr td {
      border: 3px solid black;
  }

  .table-bordered tbody tr th {
      border: 3px solid black;
  }

  .table-bordered thead tr {
      border: 3px solid black;
  }

  .table-bordered thead tr th {
      border: 3px solid black;
  }
</style>
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'wishlist_ajax.css' %}" />

<body>
    <script>
        function updateTable(){
          // clear table
          var itemCount = $(".table > tbody").children().length;
          for(var i = itemCount; i >= 2; i--){
            $(".table > tbody > tr:nth-child(" + i + ")").remove();
          }
      
          $.get("http://localhost:8000/wishlist/json/", function(data) {
            // fill table
            for(var i = 0; i < data.length; i++){
              var tr = document.createElement("tr");
              var tdNama = document.createElement("td");
              tdNama.append(data[i].fields.nama_barang);
              var tdHarga = document.createElement("td");
              tdHarga.append(data[i].fields.harga_barang);
              var tdDeskripsi = document.createElement("td");
              tdDeskripsi.append(data[i].fields.deskripsi);
              
              tr.append(tdNama);
              tr.append(tdHarga);
              tr.append(tdDeskripsi);
              
              $(".table").append(tr);
            }
          });
        }
        
        $(document).ready(function(){
          updateTable();
          
          $("#add_wishlist").click(function(){
            var nama = $("#input_nama").val();
            var harga = $("#input_harga").val();
            var deskripsi = $("#input_deskripsi").val();
      
            
            $.post("http://localhost:8000/wishlist/ajax/submit/",
            {
              nama,
              harga,
              deskripsi,
            },
            function(data, status){
              console.log("add wishlist success");
              updateTable();
              $("#input_nama").val("");
              $("#input_harga").val("");
              $("#input_deskripsi").val("");
            });
          });
        });
      </script>
      {% endblock meta %}
      
      {% block content %}
      
      <Center>
      <div class="p-4">
        <table class="table table-bordered">
            <tr>
              <th>Nama Barang</th>
              <th>Harga Barang</th>
              <th>Deskripsi</th>
            </tr>
        </table>
        <h5>Sesi terakhir login: {{ last_login }}</h5>
      
        <h5 class="mt-4">Tambah Barang</h5>
        <form method="POST" action="">
          {% csrf_token %}
          <table>
            <tr>
                <td>Nama Barang: </td>
                <td><input type="text" name="nama_barang" placeholder="Nama Barang" class="form-control" id="input_nama"></td>
            </tr>
            <tr>
                <td>Harga Barang: </td>
                <td><input type="text" name="harga_barang" placeholder="Harga Barang" class="form-control" id="input_harga"></td>
            </tr>
            <tr>
                <td>Deskripsi: </td>
                <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control" id="input_deskripsi"></td>
            </tr>
            </table>
          </form>
          <br><button id="add_wishlist" class="btn border rounded bg-warning">Tambah</button>
      </div>
      </Center>
</body>
{% endblock content %}